### PR TITLE
Update pubspec.yaml in context_watch_signals to v5

### PR DESCRIPTION
**Pull request by dickermoshe**
Fixes https://github.com/s0nerik/context_plus/issues/10

### CODE REVIEW

**Comment by s0nerik** [comment]
Thanks for your contribution, I'll merge and release it somewhere next week.

**Comment by dickermoshe** [comment]
_ping_

**Comment by s0nerik** [comment]
New release is out!

**Comment by dickermoshe** [comment]
Thank you so much for this package.
We're really loving it!

**Pull request merged**
